id: kubelet-pods

info:
  name: Kubelet Scan
  author: sharath
  severity: info
  description: Scans for kubelet pods
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kubelet,pods

http:
  - method: GET
    path:
      - "{{BaseURL}}/pods"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"PodList":'
          - '"items":'
        condition: and
