id: esmtprc-config

info:
  name: eSMTP - Config Discovery
  author: geeknik
  severity: high
  description: eSMTP configuration was discovered.
  reference:
    - https://linux.die.net/man/5/esmtprc
  metadata:
    max-request: 1
  tags: esmtp,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.esmtprc"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/plain"

      - type: word
        part: body
        words:
          - "hostname"
          - "username"
          - "password"
        condition: and

      - type: status
        status:
          - 200
