id: owncloud-config

info:
  name: owncloud Config - Detect
  author: Mahendra Purbia (Mah3Sec_)
  severity: info
  description: owncloud configuration information was detected.
  reference:
    - https://owncloud.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/owncloud/config/"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Index of'
          - 'owncloud/config'
        condition: and

      - type: status
        status:
          - 200
