id: phpcs-config

info:
  name: PHP_CodeSniffer Configuration Exposure - Detect
  author: DhiyaneshDK
  severity: info
  description: |
    PHP_CodeSniffer configuration file was detected.
  reference:
    - https://github.com/squizlabs/PHP_CodeSniffer
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"phpcs.xml"
  tags: devops,exposure,php,phpcs

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpcs.xml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'ruleset name'
          - 'rule ref='
          - '<file>'
        condition: and

      - type: word
        part: header
        words:
          - "application/xml"

      - type: status
        status:
          - 200
