id: rakefile-disclosure

info:
  name: Rakefile - File Disclosure
  author: DhiyaneshDK
  severity: info
  description: |
    Rakefile configuration file was detected.
  reference:
    - https://ruby.github.io/rake/doc/rakefile_rdoc.html
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Rakefile"
  tags: devops,exposure,rakefile,config,ruby,rails

http:
  - method: GET
    path:
      - "{{BaseURL}}/Rakefile"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - 'application.load_tasks'
          - 'config/application'
        condition: and
        case-insensitive: true

      - type: word
        part: body
        words:
          - 'require'
          - 'desc'
          - 'task :'
        condition: and
