id: robomongo-credential

info:
  name: RoboMongo Configuration File - Detect
  author: geeknik
  severity: high
  description: A MongoDB credentials file used by RoboMongo was detected.
  reference: https://robomongo.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: mongodb,robomongo,disclosure,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/db/robomongo.json"
      - "{{BaseURL}}/robomongo.json"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "application/json"

      - type: word
        words:
          - "databaseName"
          - "userName"
          - "userPassword"
          - "serverHost"
        condition: and

      - type: status
        status:
          - 200
