id: symfony-profiler

info:
  name: Symfony Profiler - Detect
  author: pdteam
  severity: high
  description: Symfony profiler was detected.
  reference: https://symfony.com/doc/current/profiler.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: http.html:"symfony Profiler"
  tags: config,exposure,symfony

http:
  - method: GET
    path:
      - "{{BaseURL}}/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app_dev.php/_profiler/empty/search/results?limit=10"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - "Symfony Profiler"
