id: producthunt

info:
  name: Producthunt User Name Information - Detect
  author: dwisiswant0
  severity: info
  description: Producthunt user name information check was conducted.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,osint-business,producthunt

self-contained: true

http:
  - method: GET
    path:
      - "https://www.producthunt.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "s profile on Product Hunt"
