id: kube-api-deployments

info:
  name: Kube API Deployments
  author: sharath
  severity: info
  description: Scans for kube deployments
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/apis/apps/v1/namespaces/default/deployments"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"DeploymentList":'
          - '"items":'
        condition: and
