id: kubernetes-resource-report

info:
  name: Detect Overview Kubernetes Resource Report
  author: pussycat0x
  severity: medium
  description: Information Disclosure of Kubernetes Resource Report
  metadata:
    max-request: 1
  tags: kubernetes,exposure,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Overview - Kubernetes Resource Report"

      - type: status
        status:
          - 200
